import { useEffect, useState } from "react";
import { Download, Volume2 } from "lucide-react";
import { artifactBlob, request, saveArtifact, saveBlob, type Artifact } from "./api";

export function ArtifactView({ artifact, onError }: { artifact: Artifact; onError: (message: string) => void }) {
  const [url, setUrl] = useState("");
  useEffect(() => {
    if (!["image", "audio"].includes(artifact.kind)) return;
    let cancelled = false;
    let address = "";
    void artifactBlob(artifact.id).then((blob) => {
      if (cancelled) return;
      address = URL.createObjectURL(blob);
      setUrl(address);
    }).catch((error: Error) => onError(error.message));
    return () => { cancelled = true; if (address) URL.revokeObjectURL(address); };
  }, [artifact.id, artifact.kind]);
  return <div className="artifact-card">
    {artifact.kind === "image" && url && <img src={url} alt="Image generated by MacBot" />}
    {artifact.kind === "image" && artifact.metadata?.width && <small>{artifact.metadata.width} × {artifact.metadata.height} · {artifact.metadata.format?.toUpperCase()}{artifact.metadata.upscaled ? " · Resized export" : ""}</small>}
    {artifact.kind === "audio" && url && <audio controls src={url} aria-label="Generated audio" />}
    <button onClick={() => void saveArtifact(artifact).catch((error: Error) => onError(error.message))}>
      <Download size={15} /> {artifact.name}
    </button>
  </div>;
}

export function ReadAloud({ messageId, available, onError }: { messageId: string; available: boolean; onError: (message: string) => void }) {
  const [loading, setLoading] = useState(false);
  const [recording, setRecording] = useState<Blob | null>(null);
  const [url, setUrl] = useState("");
  useEffect(() => {
    if (!recording) return;
    const address = URL.createObjectURL(recording);
    setUrl(address);
    return () => URL.revokeObjectURL(address);
  }, [recording]);
  async function speak() {
    setLoading(true);
    try { setRecording(await (await request(`/messages/${messageId}/speak`, { method: "POST" })).blob()); }
    catch (error) { onError((error as Error).message); }
    finally { setLoading(false); }
  }
  return <div className="read-aloud">
    <button disabled={loading || !available} title={available ? "Read this response aloud" : "Voice is preparing"} onClick={() => void speak()}><Volume2 size={14} /> {loading ? "Preparing voice…" : !available ? "Voice preparing" : "Read aloud"}</button>
    {url && <audio controls src={url} aria-label="Read this response aloud" />}
    {recording && <button onClick={() => saveBlob(recording, "MacBot-voice.wav")}>Save audio</button>}
  </div>;
}
